# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-drivers'
tap 'homebrew/services'

# Essentials
brew 'antigen'
brew 'logrotate'
brew 'gnupg'
brew 'm-cli'
brew 'pinentry-mac'
brew 'tmux'
brew 'wget'
brew 'zsh'

# Development
cask 'jetbrains-toolbox'
brew 'awscli'
brew 'composer'
brew 'git'
brew 'go'
brew 'hub'
brew 'yarn'

# Web server
brew 'certbot'
brew 'dnsmasq'
brew 'mysql@5.7'
brew 'nginx'
brew 'php'
brew 'phpmyadmin'
brew 'redis'

# Home theater
brew 'couchpotatoserver'
cask 'plex-media-server'
brew 'lftp'

# Apps
cask '1password'
cask 'a-better-finder-rename'
cask 'alfred'
cask 'atom'
cask 'bartender'
cask 'bettertouchtool'
cask 'carbon-copy-cloner'
cask 'coderunner'
cask 'daisydisk'
cask 'dash'
cask 'discord'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'hazel'
cask 'kaleidoscope'
cask 'keybase'
cask 'istat-menus'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'sequel-pro'
cask 'spotify'
cask 'steam'
cask 'transmit'
cask 'vagrant'
cask 'vlc'
cask 'virtualbox'

# Drivers
cask 'apple-hewlett-packard-printer-drivers'
cask 'canon-eos-utility'
cask 'logitech-unifying'
cask 'wacom-tablet'
cask 'yubico-yubikey-piv-manager'
